org.gradle.caching=true
group=io.ballerina.stdlib
version=2.11.2-SNAPSHOT

ballerinaLangVersion=2201.14.0-20260527-050400-74f7e6bf
axiomVersion=1.2.22
checkstylePluginVersion=10.12.0
ballerinaGradlePluginVersion=4.0.0
spotbugsPluginVersion=6.5.1
shadowJarPluginVersion=7.1.2
downloadPluginVersion=5.4.0
releasePluginVersion=3.1.0

jacocoVersion=0.8.13
quartzVersion=2.3.2

#stdlib dependencies
stdlibIoVersion=1.8.0
stdlibTimeVersion=2.7.0
stdlibUuidVersion=1.10.0
stdlibCryptoVersion=2.9.0
