[package]
org = "ballerina"
name = "task"
version = "2.11.2"
authors = ["Ballerina"]
keywords = ["task", "job", "schedule"]
repository = "https://github.com/ballerina-platform/module-ballerina-task"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.14.0-20260527-050400-74f7e6bf"

[platform.java25]
graalvmCompatible = true

[[platform.java25.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "task-native"
version = "2.11.2"
path = "../native/build/libs/task-native-2.11.2.jar"

[[platform.java25.dependency]]
groupId = "org.quartz-scheduler"
artifactId = "quartz"
version = "2.3.2"
path = "./lib/quartz-2.3.2.jar"
